---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"

# Required collections:
# - ansible.posix: For synchronize module (used in benchmark_runner)
# - community.general: For homebrew module (macOS package installation)
