---
all:
  hosts:
    sf-testing-1:
      ansible_host: 192.168.90.102
      ansible_user: parithosh
      # Host-specific benchmark configuration (overrides group_vars)
      benchmark_clients:
        - geth
        - besu
  vars:
    # Directory on remote host for benchmark execution
    workspace_root: /home/parithosh/benchmark/gas-benchmarks-v2
    # Local directory to fetch results to after execution
    local_artifacts_dir: /tmp/benchmark-results
    benchmark_runs: 1